### ISSUE TITLE
working for hs110 too

### ISSUE THREAD

**Issue by werty1st** [ggeorgovassilis/linuxscripts#2]
hello,

i can confirm that your code is also working for the HS110 model.

i would like to flash a custom image with a simple REST interface to control the smart plug.

kind regards, werty

**Comment by werty1st** [comment]
i open my device to take a photo of the circuit board. maybe somebody can identify possible serial pinouts.
![Image of AR9331-AL3A TP-Link HS100 HS110]
(https://github.com/werty1st/linuxscripts/blob/master/tp-link-hs100-smartplug/AR9331-AL3A%20TP-Link%20HS100%20HS110.png)

**Comment by ggeorgovassilis** [comment]
Hi @werty1st, thanks for the photo! While the scope of the hs100 script is indeed to operate and query the tplink hs100 wifi plug, I currently have no information about how it can be flashed with the image you are looking for. Flashing new firmware is definitely possible since tplink offers downloads for new firmware here: http://www.tp-link.us/download/HS100.html#Firmware
I'll keep this ticket open for future reference

**Comment by M1XZG** [comment]
The script is working with both my HS100 and HS110's, however, the check command isn't giving me any output other than "Connection to 172.16.29.146 9999 port [tcp/*] succeeded!"  .. it's not actually telling me if the relay is on or off.. any ideas?   

I have been able to pull that info using:

hs100.sh <IP ADDR> <PORT> status | sed -e 's/,/\n/g' | strings | grep relay | awk -F':' '{print $2}'

**Comment by ggeorgovassilis** [comment]
@M1XZG this is probably of little consolation, but it works for me. Make sure you are using the latest master branch.

**Comment by M1XZG** [comment]
LOL bugger, I had the copies of the script mixed up .. it is indeed working.  And it's a lot faster then my decode method.. ok, back to my scripts to adjust them again :D   Thanks for that.

**Comment by M1XZG** [comment]
Hm, I take it back.. I do get a result, but it shows OFF no matter what state it's in .. that's for both the HS100 and HS110

**Comment by ggeorgovassilis** [comment]
Can you open a new ticket and show the result of the "status" command?

**Comment by M1XZG** [comment]
It's actually fine. I think the issue was a version problem.  It's working
perfectly for me now.  I'll be publishing my own script that uses your
script to complete a series of tasks.

Thanks very much!

--
Robert McKenzie
rmckenzi@rpmdp.com
